# Set to TRUE if you want to check permission on parkour join
# Permission: parkour.join.<name>
# Give parkour.bypass to skip permission check and cooldown

per-parkour-permission: false

# Set MongoDB connection URI
# For more information, please see https://docs.mongodb.com/manual/reference/connection-string/

mongodb-connection-uri: "mongodb://localhost:27017/"
