per-parkour-permission: false

setup-items:
  set-start:
    material: "EMERALD"
    name: "<#12a3e6><b>Set start"
    lore:
      - "<grey>(Right Click)"
      - "<#2772e3>Set start Location of the parkour"
  set-end:
    material: "DIAMOND"
    name: "<#e07f10><b>Set end"
    lore:
      - "<grey>(Right Click on Wall Sign)"
      - "<#2772e3>Set end Location of the parkour"
  wand:
    material: "BLAZE_ROD"
    name: "<#e8bc38><b>Region<#2772e3><b>Wand"
    lore:
      - "<grey>(Left Click on block) <#2772e3><b>Pos-1"
      - "<grey>(Right Click on block) <#2772e3><b>Pos-2"
  complete-player-cmd:
    material: "PAPER"
    name: "<#b229c2><b>Set player commands"
    lore:
      - "<grey>(Right Click) <#2772e3>Add commands"
      - "<grey>(Shift + Left Click) <#2772e3>Delete all commands"
  complete-console-cmd:
    material: "MAP"
    name: "<#b229c2><b>Set console commands"
    lore:
      - "<grey>(Right Click) <#2772e3>Add commands"
      - "<grey>(Shift + Left Click) <#2772e3>Delete all commands"
  set-cooldown:
    material: "CLOCK"
    name: "<#96e823><b>Set cooldown"
    lore:
      - "<grey>(Right Click)"
      - "<#2772e3>Set cooldown Parkour"
  save:
    material: "BOOK"
    name: "<#10d40d><b>Save Parkour"
    lore:
      - "<grey>(Right Click)"
      - "<#2772e3>Save parkour"
  cancel:
    material: "BARRIER"
    name: "<#c91818><b>Cancel"
    lore:
      - "<grey>(Right Click)"
      - "<#2772e3>Exit setup without save"

parkour-item:
  leave:
    material: "BARRIER"
    name: "<#d63e4d><b>Leave"
    lore:
      - "<grey>(Right Click)"
      - "<#2772e3>Leave parkour"

complete-wall-sign:
  one: "{PREFIX}"
  two: ""
  three: "<green>{PARKOUR}"
  four: "<grey>Click to complete"

# Commands run by Player when quit parkour
commands-on-quit:
  - "cmd"

# - For more information, please see https://docs.mongodb.com/manual/reference/connection-string/
mongodb-connection-uri: "mongodb://localhost:27017/"